require "nutrientes/version"
require "nutrientes/alimento"
require "nutrientes/list"
require "nutrientes/glucosa"
# Module generated by Bundler for gem Nutrientes
module Nutrientes
  # Your code goes here...
end
